// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIlG-4wV_8c0kqD_9SqkaK_lBr3ijfQgw',
    appId: '1:120461528244:web:9d3e12067f1ad3d7691be1',
    messagingSenderId: '120461528244',
    projectId: 'pueblos-firebase-demo',
    authDomain: 'pueblos-firebase-demo.firebaseapp.com',
    storageBucket: 'pueblos-firebase-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzMWzTTiNzP4rynX1nUjOTRcoPCB_pjHI',
    appId: '1:120461528244:android:573613540d971049691be1',
    messagingSenderId: '120461528244',
    projectId: 'pueblos-firebase-demo',
    storageBucket: 'pueblos-firebase-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIJJ6VucWyEUV-vyvkJA3Fnql1myxYix4',
    appId: '1:120461528244:ios:4b0b0731a5f8d96b691be1',
    messagingSenderId: '120461528244',
    projectId: 'pueblos-firebase-demo',
    storageBucket: 'pueblos-firebase-demo.appspot.com',
    iosBundleId: 'com.example.stateChangeDemo',
  );

}